/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export type { ResearchRegistry } from "./ResearchRegistry.js";
export * as factories from "./factories/index.js";
export { ResearchRegistry__factory } from "./factories/ResearchRegistry__factory.js";
